#! /bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

function execute_with_output() {
  echo "  --> $@"
  $@
}

source "$DIR/ensure-rvm.sh"
source "$DIR/ensure-bundler.sh"
source "$DIR/ensure-vagrant.sh"

echo "Updating gems"
echo "  --> bundle install"
# Bundle while reducing excess noise.
bundle install | grep -v 'Using' | sed '/^$/d'

echo
echo "Updating cookbooks"
execute_with_output bundle exec librarian-chef install

echo
echo "Running vagrant"
if [ $# == 0 ]; then
  vagrant up --provision
else
  execute_with_output vagrant $@
fi

[ $? == 0 ] && source "$DIR/add-local-url-to-hosts.sh"
